// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSGuuEt5T6jZTVCmbfna9wXHw2vvFSx9I',
    appId: '1:697362377676:web:2b01a11c7c8f82bf43cb69',
    messagingSenderId: '697362377676',
    projectId: 'fir-flutter-codelab-a1705',
    authDomain: 'fir-flutter-codelab-a1705.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-a1705.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcdIgBon1kJAc0ln3_RVd7ODzliQBudAg',
    appId: '1:697362377676:android:0563069bbd7b750743cb69',
    messagingSenderId: '697362377676',
    projectId: 'fir-flutter-codelab-a1705',
    storageBucket: 'fir-flutter-codelab-a1705.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcuH9UuP8g4QMnUMsqGU57WQLFsxvUxtc',
    appId: '1:697362377676:ios:17c2e35ee0c188c943cb69',
    messagingSenderId: '697362377676',
    projectId: 'fir-flutter-codelab-a1705',
    storageBucket: 'fir-flutter-codelab-a1705.appspot.com',
    iosClientId: '697362377676-jrsc55t7r811f37fta8il2skkift41k2.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcuH9UuP8g4QMnUMsqGU57WQLFsxvUxtc',
    appId: '1:697362377676:ios:17c2e35ee0c188c943cb69',
    messagingSenderId: '697362377676',
    projectId: 'fir-flutter-codelab-a1705',
    storageBucket: 'fir-flutter-codelab-a1705.appspot.com',
    iosClientId: '697362377676-jrsc55t7r811f37fta8il2skkift41k2.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
